name: Build APK Simple

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Notes de release'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Make gradlew executable
      run: chmod +x ./android/gradlew
      
    - name: Build APK
      run: |
        cd android
        ./gradlew assembleRelease --no-daemon
        
    - name: Get version info
      id: version
      run: |
        # Lire la version depuis app.json
        version=$(grep '"version"' app.json | sed 's/.*"version": *"\([^"]*\)".*/\1/')
        
        # Lire le build number depuis build.gradle
        build=$(grep "versionCode" android/app/build.gradle | sed 's/.*versionCode //')
        
        echo "version=$version" >> $GITHUB_OUTPUT
        echo "build=$build" >> $GITHUB_OUTPUT
        echo "apk_name=inovie-scan-v$version-$build.apk" >> $GITHUB_OUTPUT
        
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk-file
        path: android/app/build/outputs/apk/release/app-release.apk
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.version }}-${{ steps.version.outputs.build }}
        name: Version ${{ steps.version.outputs.version }} (${{ steps.version.outputs.build }})
        body: |
          ## Version ${{ steps.version.outputs.version }} (${{ steps.version.outputs.build }})
          
          ${{ github.event.inputs.release_notes || 'Build automatique via GitHub Actions' }}
          
          ### Téléchargement
          - Téléchargez l'APK ci-dessous
          - Installez-le sur votre appareil Android
          
          ### Informations
          - Version: ${{ steps.version.outputs.version }}
          - Build: ${{ steps.version.outputs.build }}
          - Date: $(date)
        draft: false
        prerelease: false
        files: android/app/build/outputs/apk/release/app-release.apk
        
    - name: Success message
      run: |
        echo "✅ Build terminé avec succès !"
        echo "📱 APK: ${{ steps.version.outputs.apk_name }}"
        echo "🏷️ Tag: v${{ steps.version.outputs.version }}-${{ steps.version.outputs.build }}"
